config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  get 'static/home'
  get 'static/info'
  get 'static/admin'
  get 'books/bytitle'
  get 'books/byyear'
  get 'books/byrating'
  get 'movies/bytitle'
  get 'movies/byyear'
  get 'movies/byrating'
  get 'songs/bytitle'
  get 'songs/byyear'
  get 'songs/byrating'
  get 'dramas/bytitle'
  get 'dramas/byyear'
  get 'dramas/byrating'

  resources :books do 
  	resources :bookreviews
    resources :bookreps
  end	
  resources :movies do 
  	resources :moviereviews
    resources :moviereps
  end	
  resources :songs do 
  	resources :songreviews
    resources :songreps
  end	
  resources :dramas do 
  	resources :dramareviews
    resources :dramareps
  end	

  root 'static#home'
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :bookreviews
	has_many :bookreps

	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/


	def self.search(search)
  		if search
    		@book = Book.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@book = Book.all.order('created_at DESC') 
  		end
	end
	
end

app/models/bookrep.rb
class Bookrep < ApplicationRecord

	belongs_to :user
	belongs_to :book
end

app/models/bookreview.rb
class Bookreview < ApplicationRecord
	validates :user_id, :uniqueness => { :scope => :book_id }

	belongs_to :user
	belongs_to :book
end

app/models/drama.rb
class Drama < ApplicationRecord
	
	belongs_to :user
	has_many :dramareviews
	has_many :dramareps

	has_attached_file :drama_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :drama_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@drama = Drama.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
 		else
   			@drama = Drama.all.order('created_at DESC') 
 		end
	end

end

app/models/dramarep.rb
class Dramarep < ApplicationRecord
	belongs_to :user
	belongs_to :drama
end

app/models/dramareview.rb
class Dramareview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :drama_id }

	belongs_to :user
	belongs_to :drama  
end

app/models/movie.rb
class Movie < ApplicationRecord
	
	belongs_to :user
	has_many :moviereviews
	has_many :moviereps

	has_attached_file :mov_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :mov_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
    		@movie = Movie.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
    		@movie = Movie.all.order('created_at DESC') 
  		end
	end
	
end

app/models/movierep.rb
class Movierep < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/moviereview.rb
class Moviereview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :movie_id }

	belongs_to :user
	belongs_to :movie
end

app/models/song.rb
class Song < ApplicationRecord
	
	belongs_to :user
	has_many :songreviews
	has_many :songreps

	
	has_attached_file :song_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :song_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@song = Song.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@song = Song.all.order('created_at DESC') 
  		end
	end

end

app/models/songrep.rb
class Songrep < ApplicationRecord
	belongs_to :user
	belongs_to :song
end

app/models/songreview.rb
class Songreview < ApplicationRecord
	
	validates :user_id, :uniqueness => { :scope => :song_id }

	belongs_to :user
	belongs_to :song
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
	has_many :books
	has_many :movies
	has_many :songs
	has_many :dramas

  has_many :bookreps
  
  has_one :bookreview
  has_one :moviereview
  has_one :songreview
  has_one :dramareview
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :set_user_name

  private
    def set_user_name
       self.user_name = self.nickname + self.id.to_s;
    end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action  :find_movie, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def index
		@movie = Movie.all
  		if params[:search]
    		@movie = Movie.search(params[:search]).order("created_at DESC")
  		else
    		@movie = Movie.all.order('created_at DESC')
  		end
	end

	def bytitle
		@movie = Movie.all
  		if params[:search]
    		@movie = Movie.search(params[:search]).order("title")
  		else
    		@movie = Movie.all.order('title')
  		end
	end

	def byyear
		@movie = Movie.all
  		if params[:search]
    		@movie = Movie.search(params[:search]).order("release_year DESC")
  		else
    		@movie = Movie.all.order('release_year DESC')
  		end
	end

	def byrating
		@movie = Movie.all
		@movie.each do |movie|
			if movie.moviereviews.blank?
		   		@average_moviereview = 0
			else
				@average_moviereview = movie.moviereviews.average(:rating).round(2)
			end
			movie.update_attribute(:avgrating, @average_moviereview )
		end
  		if params[:search]
    		@movie = Movie.search(params[:search]).order("avgrating DESC")
  		else
    		@movie = Movie.all.order('avgrating DESC')
  		end
	end

	def show
		@us = User.all
		if @movie.moviereviews.blank?
		   @average_moviereview = 0
		else
			@average_moviereview = @movie.moviereviews.average(:rating).round(2)
		end	
	end

	def new
		@movie = current_user.movies.build
	end	

	def create
		@movie = current_user.movies.build(movie_params)
		if @movie.save
			redirect_to movies_path
		else
			render 'new'
		end
	end

	def edit
		if current_user != @movie.user && current_user.usertype != 779
   			 redirect_to movie_path(@movie)
  		end
	end

	def update
		if @movie.update(movie_params)
			redirect_to movie_path(@movie)
		else
			render 'edit'
		end
	end

	def destroy
		@movie.destroy
    	redirect_to movies_path
	end

	private 
		def movie_params
			params.require(:movie).permit(:title, :release_year, :stars, :director, :mov_img, :avgrating)
		end

		def find_movie
			@movie = Movie.find(params[:id])
		end
end

app/helpers/bookreps_helper.rb
module BookrepsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/songreps_helper.rb
module SongrepsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
	<%= f.file_field :mov_img %>
	<%= f.input :title, label:"Movie Title" %>
	<%= f.input :stars, label:"Stars" %>
	<%= f.input :director, label:"Director" %>
	<%= f.input :release_year, label:"Released Year" %> 
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/movies/byrating.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Movies</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add movie", new_movie_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(movies_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= movies_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= movies_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= movies_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= movies_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Movies</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @movie.count == 0 %>
                            <h4 style="margin-left: 40px;"> No Movie Available </h4>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @movie.each do |movie| %>
                                <!--<h3> <%= link_to movie.title, movie_path(movie) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/movies/<%= movie.id %>">
                                    <%= image_tag movie.mov_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/movies/bytitle.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Movies</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add movie", new_movie_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(movies_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= movies_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= movies_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= movies_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= movies_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Movies</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @movie.count == 0 %>
                           <h4 style="margin-left: 40px;"> No Movie Available </h4>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @movie.each do |movie| %>
                                <!--<h3> <%= link_to movie.title, movie_path(movie) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/movies/<%= movie.id %>">
                                    <%= image_tag movie.mov_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/movies/byyear.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Movies</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add movie", new_movie_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(movies_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= movies_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= movies_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= movies_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= movies_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Movies</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @movie.count == 0 %>
                            <h4 style="margin-left: 40px;"> No Movie Available </h4>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @movie.each do |movie| %>
                                <!--<h3> <%= link_to movie.title, movie_path(movie) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/movies/<%= movie.id %>">
                                    <%= image_tag movie.mov_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/movies/edit.html.erb
<head><title>Edit Movie</title></head>
<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #2D4159;">
	<div class="edit-book-form">
		<h1>Edit Form</h1>
		<%= render 'form' %>
	</div>
</div>     

app/views/movies/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Movies</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add Movie", new_movie_path %> </li>

                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

       <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(movies_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                    <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= movies_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= movies_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= movies_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= movies_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Movies</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @movie.count == 0 %>
                            <h4 style="margin-left: 40px;"> No Movie Available </h4>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @movie.each do |movie| %>
                                <!--<h3> <%= link_to movie.title, movie_path(movie) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/movies/<%= movie.id %>">
                                    <%= image_tag movie.mov_img.url(:book_index), class: "book" %>
                                </a>
                                </div>
                            <% end %>
                            <% end %>
                        </div> 
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/movies/new.html.erb
<head><title>New Moview</title></head>

<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #374785;">
	<div class="new-book-form">
		<h1>New Movie</h1>
		<%= render 'form' %>
	</div>
</div> 