config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  get 'static/home'
  get 'static/info'
  get 'static/admin'
  get 'books/bytitle'
  get 'books/byyear'
  get 'books/byrating'
  get 'movies/bytitle'
  get 'movies/byyear'
  get 'movies/byrating'
  get 'songs/bytitle'
  get 'songs/byyear'
  get 'songs/byrating'
  get 'dramas/bytitle'
  get 'dramas/byyear'
  get 'dramas/byrating'

  resources :books do 
  	resources :bookreviews
    resources :bookreps
  end	
  resources :movies do 
  	resources :moviereviews
    resources :moviereps
  end	
  resources :songs do 
  	resources :songreviews
    resources :songreps
  end	
  resources :dramas do 
  	resources :dramareviews
    resources :dramareps
  end	

  root 'static#home'
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :bookreviews
	has_many :bookreps

	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/


	def self.search(search)
  		if search
    		@book = Book.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@book = Book.all.order('created_at DESC') 
  		end
	end
	
end

app/models/bookrep.rb
class Bookrep < ApplicationRecord

	belongs_to :user
	belongs_to :book
end

app/models/bookreview.rb
class Bookreview < ApplicationRecord
	validates :user_id, :uniqueness => { :scope => :book_id }

	belongs_to :user
	belongs_to :book
end

app/models/drama.rb
class Drama < ApplicationRecord
	
	belongs_to :user
	has_many :dramareviews
	has_many :dramareps

	has_attached_file :drama_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :drama_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@drama = Drama.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
 		else
   			@drama = Drama.all.order('created_at DESC') 
 		end
	end

end

app/models/dramarep.rb
class Dramarep < ApplicationRecord
	belongs_to :user
	belongs_to :drama
end

app/models/dramareview.rb
class Dramareview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :drama_id }

	belongs_to :user
	belongs_to :drama  
end

app/models/movie.rb
class Movie < ApplicationRecord
	
	belongs_to :user
	has_many :moviereviews
	has_many :moviereps

	has_attached_file :mov_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :mov_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
    		@movie = Movie.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
    		@movie = Movie.all.order('created_at DESC') 
  		end
	end
	
end

app/models/movierep.rb
class Movierep < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/moviereview.rb
class Moviereview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :movie_id }

	belongs_to :user
	belongs_to :movie
end

app/models/song.rb
class Song < ApplicationRecord
	
	belongs_to :user
	has_many :songreviews
	has_many :songreps

	
	has_attached_file :song_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :song_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@song = Song.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@song = Song.all.order('created_at DESC') 
  		end
	end

end

app/models/songrep.rb
class Songrep < ApplicationRecord
	belongs_to :user
	belongs_to :song
end

app/models/songreview.rb
class Songreview < ApplicationRecord
	
	validates :user_id, :uniqueness => { :scope => :song_id }

	belongs_to :user
	belongs_to :song
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
	has_many :books
	has_many :movies
	has_many :songs
	has_many :dramas

  has_many :bookreps
  
  has_one :bookreview
  has_one :moviereview
  has_one :songreview
  has_one :dramareview
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :set_user_name

  private
    def set_user_name
       self.user_name = self.nickname + self.id.to_s;
    end

end

app/controllers/songreviews_controller.rb
class SongreviewsController < ApplicationController
	before_action :find_song
	before_action :find_songreview, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	$r = 0
	$c = 0

	def new
		@songreview = Songreview.new
	end
	
	def create
		@songreview = Songreview.new(songreview_params)
		@songreview.song_id =@song.id
		@songreview.user_id = current_user.id

		if @songreview.rating > 5 || @songreview.rating < 0
			Songreview.last.destroy
			render 'edit'
		elsif @songreview.save
			redirect_to song_path(@song)
		else
			flash[:success] = "Users may only write one review per Song."
			redirect_to song_path(@song)
		end	
	end

	def edit
		if current_user != @songreview.user
   			 redirect_to song_path(@song)
  		end
  		$r = @songreview.rating
  		$c = @songreview.comment
	end

	def update 
		if @songreview.update(songreview_params)
			if(@songreview.rating > 5 || @songreview.rating < 0)
				@songreview.update_attribute(:rating, $r)
				@songreview.update_attribute(:comment, $c)
				flash[:success] = "Valid Rating is from 1 to 5"
				redirect_to song_path(@song)
			else
				redirect_to song_path(@song)
			end
		else 
			render 'edit'
		end	
	end

	def destroy
		@songreview.destroy
		redirect_to song_path(@song)
	end	
	
	private

		def songreview_params
			 params.require(:songreview).permit(:rating,:comment)
		end	

		def find_song
			@song = Song.find(params[:song_id])
	 	end

	 	def find_songreview
	 		@songreview = Songreview.find(params[:id])
	 	end	
end

app/helpers/bookreps_helper.rb
module BookrepsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/songreviews_helper.rb
module SongreviewsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/songreviews/_form.html.erb
<%= simple_form_for([@song, @song.songreviews.build])  do |f| %>
	
	<%= f.input :rating, label:"Rating (Enter a value between 0 to 5)"%>
	<%= f.input :comment %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/songreviews/_songreview.html.erb
<div class="review">	
	<p class="review-rating"> Rating : <%= songreview.rating %></p>
	<p class="review-comment"> <%= songreview.comment %></p>
	<h4> rated by <% @us.each do |us| %>
		<% if us.id == songreview.user_id %>
			<%= us.user_name %>
		<% end %>
	<% end %>
	</h4>
		<% if user_signed_in? %>
			<% if songreview.user_id == current_user.id  %>
				<div class="links btn-group">
					<%= link_to "Edit", edit_song_songreview_path(songreview.song, songreview) ,class:"btn btn-custom" %> 
					<%= link_to "Delete", song_songreview_path(songreview.song, songreview), method: :delete, data: { confirm: "Are you sure?" } ,class:"btn btn-custom" %>
				</div>
			<% elsif current_user.usertype == 779 %>
				<div class="links btn-group">
					<%= link_to "Delete", song_songreview_path(songreview.song, songreview), method: :delete, data: { confirm: "Are you sure?" } ,class:"btn btn-custom" %>
				</div>	
			<% end %>
		<% end %>		
</div>	 

app/views/songreviews/edit.html.erb
<head><title>Edit Review</title></head>
<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #5D5C61;">
    <div class="edit-review-form">
		<h1> Edit Review </h1>

		<%= simple_form_for([@song,@songreview]) do |f| %>
			<%= f.input :rating, label:"Rating (Enter a value between 0 to 5)" %>
			<%= f.input :comment %>
			<%= f.button :submit,:class=> 'btn-custom2' %>
		<% end %>
	</div>
</div>		

app/views/songreviews/new.html.erb
<head><title>New Review</title></head>
<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #E98074;">
    <div class="new-review-form">
		<h1>New Review </h1>
		<%= render 'form' %>
	</div>
</div>		