config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  get 'static/home'
  get 'static/info'
  get 'static/admin'
  get 'books/bytitle'
  get 'books/byyear'
  get 'books/byrating'
  get 'movies/bytitle'
  get 'movies/byyear'
  get 'movies/byrating'
  get 'songs/bytitle'
  get 'songs/byyear'
  get 'songs/byrating'
  get 'dramas/bytitle'
  get 'dramas/byyear'
  get 'dramas/byrating'

  resources :books do 
  	resources :bookreviews
    resources :bookreps
  end	
  resources :movies do 
  	resources :moviereviews
    resources :moviereps
  end	
  resources :songs do 
  	resources :songreviews
    resources :songreps
  end	
  resources :dramas do 
  	resources :dramareviews
    resources :dramareps
  end	

  root 'static#home'
end

app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user
	has_many :bookreviews
	has_many :bookreps

	has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/


	def self.search(search)
  		if search
    		@book = Book.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@book = Book.all.order('created_at DESC') 
  		end
	end
	
end

app/models/bookrep.rb
class Bookrep < ApplicationRecord

	belongs_to :user
	belongs_to :book
end

app/models/bookreview.rb
class Bookreview < ApplicationRecord
	validates :user_id, :uniqueness => { :scope => :book_id }

	belongs_to :user
	belongs_to :book
end

app/models/drama.rb
class Drama < ApplicationRecord
	
	belongs_to :user
	has_many :dramareviews
	has_many :dramareps

	has_attached_file :drama_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :drama_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@drama = Drama.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
 		else
   			@drama = Drama.all.order('created_at DESC') 
 		end
	end

end

app/models/dramarep.rb
class Dramarep < ApplicationRecord
	belongs_to :user
	belongs_to :drama
end

app/models/dramareview.rb
class Dramareview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :drama_id }

	belongs_to :user
	belongs_to :drama  
end

app/models/movie.rb
class Movie < ApplicationRecord
	
	belongs_to :user
	has_many :moviereviews
	has_many :moviereps

	has_attached_file :mov_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :mov_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
    		@movie = Movie.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
    		@movie = Movie.all.order('created_at DESC') 
  		end
	end
	
end

app/models/movierep.rb
class Movierep < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/models/moviereview.rb
class Moviereview < ApplicationRecord

	validates :user_id, :uniqueness => { :scope => :movie_id }

	belongs_to :user
	belongs_to :movie
end

app/models/song.rb
class Song < ApplicationRecord
	
	belongs_to :user
	has_many :songreviews
	has_many :songreps

	
	has_attached_file :song_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :song_img, content_type: /\Aimage\/.*\z/

	def self.search(search)
  		if search
   			@song = Song.all.where('title LIKE ?', "%#{search}%").order('created_at DESC')
  		else
   			@song = Song.all.order('created_at DESC') 
  		end
	end

end

app/models/songrep.rb
class Songrep < ApplicationRecord
	belongs_to :user
	belongs_to :song
end

app/models/songreview.rb
class Songreview < ApplicationRecord
	
	validates :user_id, :uniqueness => { :scope => :song_id }

	belongs_to :user
	belongs_to :song
end

app/models/static.rb
class Static < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
	has_many :books
	has_many :movies
	has_many :songs
	has_many :dramas

  has_many :bookreps
  
  has_one :bookreview
  has_one :moviereview
  has_one :songreview
  has_one :dramareview
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :set_user_name

  private
    def set_user_name
       self.user_name = self.nickname + self.id.to_s;
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action  :find_song, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	def index
		@song = Song.all
  		if params[:search]
    		@song = Song.search(params[:search]).order("created_at DESC")
  		else
    		@song = Song.all.order('created_at DESC')
  		end
	end

	def bytitle
		@song = Song.all
  		if params[:search]
    		@song = Song.search(params[:search]).order("title")
  		else
    		@song = Song.all.order('title')
  		end
	end

	def byyear
		@song = Song.all
  		if params[:search]
    		@song = Song.search(params[:search]).order("release_year DESC")
  		else
    		@song = Song.all.order('release_year DESC')
  		end
	end

	def byrating
		@song = Song.all
		@song.each do |song|
			if song.songreviews.blank?
		   		@average_songreview = 0
			else
				@average_songreview = song.songreviews.average(:rating).round(2)
			end
			song.update_attribute(:avgrating, @average_songreview )
		end
  		if params[:search]
    		@song = Song.search(params[:search]).order("avgrating DESC")
  		else
    		@song = Song.all.order('avgrating DESC')
  		end
	end

	def show
		@us = User.all
		if @song.songreviews.blank?
		   @average_songreview = 0
		else
			@average_songreview = @song.songreviews.average(:rating).round(2)
		end	
	end

	def new
		@song = current_user.songs.build
	end	

	def create
		@song = current_user.songs.build(song_params)
		if @song.save
			redirect_to songs_path
		else
			render 'new'
		end
	end

	def edit
		if current_user != @song.user && current_user.usertype != 779
   			 redirect_to song_path(@song)
  		end
	end

	def update
		if @song.update(song_params)
			redirect_to song_path(@song)
		else
			render 'edit'
		end
	end

	def destroy
		@song.destroy
    	redirect_to songs_path
	end

	private 
		def song_params
			params.require(:song).permit(:title, :release_year, :artist, :song_img, :avgrating)
		end

		def find_song
			@song = Song.find(params[:id])
		end
end

app/helpers/bookreps_helper.rb
module BookrepsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dramareps_helper.rb
module DramarepsHelper
end

app/helpers/dramas_helper.rb
module DramasHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/songreps_helper.rb
module SongrepsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for @song do |f| %>
	<%= f.file_field :song_img %>
	<%= f.input :title, label:"Song Title" %>
	<%= f.input :release_year, label:"Released Year" %> 
	<%= f.input :artist, label:"Artist" %>
	<%= f.button :submit, :class => "btn-custom2" %>
<% end %>

app/views/songs/byrating.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Songs</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add song", new_song_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(songs_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= songs_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= songs_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= songs_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= songs_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Songs</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @song.count == 0 %>
                            <h3 style="margin-left: 40px;"> No Song Available </h3>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @song.each do |song| %>
                                <!--<h3> <%= link_to song.title, song_path(song) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/songs/<%= song.id %>">
                                    <%= image_tag song.song_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/songs/bytitle.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Songs</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add song", new_song_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(songs_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= songs_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= songs_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= songs_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= songs_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Songs</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @song.count == 0 %>
                            <h3 style="margin-left: 40px;"> No Song Available </h3>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @song.each do |song| %>
                                <!--<h3> <%= link_to song.title, song_path(song) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/songs/<%= song.id %>">
                                    <%= image_tag song.song_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/songs/byyear.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Songs</title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                        <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                    <% end %>
                <li class="bgr"> <%= link_to "Add song", new_song_path %> </li>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>   
            </ul>
        </div> 

        <div class="row-2" style="width:300px; float:right; font-size:24px; color:#b9b9b9;  padding:4px 9px 6px 9px; margin-right:10px;">
            <%= form_tag(songs_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search", size: "20" %>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                     <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                    <li> <a href= "<%= songs_path %> "> Uploaded Date</a> </li>
                    <li> <a href="<%= songs_bytitle_path %> "> Name</a> </li>
                    <li> <a href="<%= songs_byyear_path %>"> Released Year </a> </li>
                    <li> <a href="<%= songs_byrating_path %>"> Rating </a> </li>
                    
                </ul>
            </div>               

            <div id="content_box"> 
                <div style=" width:1100px; float:left; margin-left:10px;">
                    <div class="bg-grey">
                        <div class="padding-1">
                            <div class="wrapper">
                                <font color="Purple" size="4">Songs</font>
                            </div>
                        </div>
                    </div>
                    <div style="font-size:14px;" class="box" width = "100%" hight = "1010">
                        <div class="row">
                        <% if @song.count == 0 %>
                            <h3 style="margin-left: 40px;"> No Song Available </h3>
                        <% else %>
                            <% @cnt = 0 %>
                            <% @song.each do |song| %>
                                <!--<h3> <%= link_to song.title, song_path(song) %> </h3>-->
                                <div class="col-md-3" >
                                <% @cnt = @cnt + 1 %>
                                <% if @cnt%4 == 1 %>
                                    <br><br>
                                <% elsif @cnt%4 == 2 %>
                                    <br><br><br><br>
                                <% elsif @cnt%4 == 3 %>
                                    <br><br><br><br><br><br>
                                <% elsif @cnt%4 == 0 %>
                                    <br><br><br><br><br><br><br><br>
                                <% end %>
                                <a href="/songs/<%= song.id %>">
                                   <%= image_tag song.song_img.url(:book_index), class: "book" %>
                                </a>
                            </div>
                            <% end %>
                            <% end %>
                        </div>
                        
                    </div>     
                </div>
            </div>                                                                                                                                       
        </section>
        
        <hr>
        
        <footer>
            <div>
                <ul>
                    <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
                </ul>
            </div>
        </footer>

    </body>
    </html>

app/views/songs/edit.html.erb
<head><title>Edit song</title></head>

<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #61892F;">
	<div class="edit-book-form">
		<h1>Edit Form</h1>
		<%= render 'form' %>
	</div>
</div>     

app/views/songs/new.html.erb
<head><title>New song</title></head>
<div class="col-md-6 col-md-offset-3 new-book-form", style= "margin-top: 200px; background-color: #D83F87;">
	<div class="new-book-form">
		<h1>New Song</h1>
		<%= render 'form' %>
	</div>
</div>  

app/views/songs/show.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= @song.title %></title>
</head>
<body id="page1">
    <a name="top"></a>
    <header>    
        <div class="row-1">
            <ul  class="sf-menu">
                <li class="bgr"> <%= link_to "Rateit", root_path %></li>
                <li class="bgr"> <%= link_to "Book", books_path %></li>
                <li class="bgr"> <%= link_to "Movie", movies_path %></li>
                <li class="bgr"> <%= link_to "Song", songs_path %></li>
                <li class="bgr"> <%= link_to "Drama Series", dramas_path %></li>
                <li class="bgr"> <%= link_to "About us", static_info_path %></li>
                <% if user_signed_in? %>
                <li class="bgr"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                <li class="bgr"> <%= link_to current_user.user_name, edit_registration_path(current_user) %> </li>
                <% if current_user.usertype == 779 %>
                <li class="bgr"> <%= link_to "Admin", static_admin_path %></li>
                <% end %>
                <% else %>
                <li class="bgr"> <%= link_to "Sign Up", new_user_registration_path %></li>
                <li class="bgr"> <%= link_to "Log In", new_user_session_path %> </li>
                <% end %>  
            </ul>
        </div> 
        <div class="row-2">
            <% flash.each do |key, value| %>
            <div><%= value %></div>
            <% end %>
        </div>
    </header>

    <section id="content">   
        <div class="wrapper">
            <div style=" width:180px; float:left; margin-left:10px;">
                <ul class="list-1">
                 <div style="color:#8c8c8c; text-align:center; padding:6px; background-color: #ededed; font-size:14px;"> Order By </div>
                 <li> <a href= "<%= songs_path %> "> Uploaded Date</a> </li>
                 <li> <a href="<%= songs_bytitle_path %> "> Name</a> </li>
                 <li> <a href="<%= songs_byyear_path %>"> Released Year </a> </li>
                 <li> <a href="<%= songs_byrating_path %>"> Rating </a> </li>

             </ul>
         </div>               

         <div id="content_box"> 
            <div style=" width:1100px; float:left; margin-left:10px;">
                <div class="bg-grey">
                    <div class="padding-1">
                        <div class="wrapper">
                            <font color="Purple" size="4"><%= @song.title %></font>
                        </div>
                    </div>
                </div>
                <div style="font-size:14px;" class="box" width = "100%" height = "1010">
                    <div class="row">
                        <div class="col-md-4">
                            <%= image_tag @song.song_img.url(:book_show), class: "book-show" %>
                            <br>
                            <br>
                            <div class="links btn_group">
                                <% if user_signed_in? %>
                                <%= link_to "Add Review",  new_song_songreview_path(@song), class:"btn btn-custom"  %>
                                <%= link_to "Add Comment",  new_song_songrep_path(@song), class:"btn btn-custom"  %>
                                <% end %>
                                <%= link_to "Back", songs_path, class:"btn btn-custom"  %>
                                <% if user_signed_in? %>
                                <% if @song.user_id == current_user.id  || current_user.usertype == 779 %>
                                <%= link_to "Edit", edit_song_path(@song), class:"btn btn-custom"  %>
                                <%= link_to "Delete", song_path(@song), method: :delete, data: { confirm: "Are You Sure?" }, class:"btn btn-custom"  %>
                                <% end %>
                                <% end %>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="book-info">
                                <h4 class="song_artist"> Artist : <%= @song.artist %> </h4>
                                <h4 class="releeased_year"> Released Year : <%= @song.release_year %> </h4>
                                <h2 class="avg_rating"> Average Rating : <%= @average_songreview %></h2>
                                <span class="number_of_reviews">Based on <%= @song.songreviews.count %> reviews </span>
                            </div>    
                            <br><br>
                            
                            <div class="reviews">
                                <h1>Reviews</h1>
                                <%= render @song.songreviews.all.order('created_at DESC')  %>
                                <%= render @song.songreps.all.order('created_at DESC')  %>
                            </div>    
                        </div>
                    </div>
                </div>     
            </div>
        </div>    
    </div>                                                                                                                                   
</section>

<hr>

<footer>
    <div>
        <ul>
            <li style="margin-left: 800px"><a href="#top">Go to top</a></li>
        </ul>
    </div>
</footer>

</body>
</html>